# Generated by Django 3.2.9 on 2021-11-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineName',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('salt_name', models.CharField(blank=True, max_length=255, null=True)),
                ('drug_form', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=255, null=True)),
                ('strength', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
